#:kivy 2.0.0
#:import platform kivy.utils.platform
#:include LoginScreen login_screen.LoginScreen
#:include NewRegister new_register.NewRegister
#:include InitialScreen initial_screen.InitialScreen
#:include NewObject new_object.NewObject

<MainScreenManager>
    LoginScreen:
        name: 'loginscreen'
    NewRegister:
        name: 'newregister'
    InitialScreen:
        name: 'initialscreen'
    NewObject:
        name: 'newobject'
